describe('Registration launch', () => {
  it('launch app', () => {
    cy.visit('https://parabank.parasoft.com/parabank/index.htm')
    cy.get('#loginPanel > :nth-child(3) > a').click()
    cy.get("input[id='customer.firstName']").type('Aloo')
    cy.get("input[id='customer.lastName']").type('hai')
    cy.get("input[id='customer.address.street']").type('Gedangan')
    cy.get("input[id='customer.address.city']").type('jakarta')
    cy.get("input[id='customer.address.state']").type('DKI Jakarta')
    cy.get("input[id='customer.address.zipCode']").type('40001')
    cy.get("input[id='customer.phoneNumber']").type('0823423432')
    cy.get("input[id='customer.ssn']").type('9999999')
    cy.get("input[id='customer.username']").type('Kei')
    cy.get("input[id='customer.password']").type('kei123')
    cy.get("#repeatedPassword").type('kei123')
    cy.get('[colspan="2"] > .button').click()
    cy.get("span[id='customer.username.errors']").should('have.text', 'This username already exists.')
    //cy.get("span[id='customer.username.errors']").contains('This username already exists')
  })
})